CREATE OR REPLACE PROCEDURE RIGHT_SIZE_TABLE_COLUMNS(DB_STR VARCHAR,  SCHEMA_STR VARCHAR, TABLE_NAME_STR VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    QUERY STRING;
    FINAL_QUERY STRING;
    OUTPUT_MSG STRING;
BEGIN
    FINAL_QUERY := 'CREATE OR REPLACE TABLE '||TABLE_NAME_STR || ' AS SELECT ';

    QUERY := 'SELECT
            COLUMN_NAME,
            CHARACTER_MAXIMUM_LENGTH,
            IS_NULLABLE
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_CATALOG            = UPPER('''||:DB_STR||''')
          AND TABLE_SCHEMA             = UPPER('''||:SCHEMA_STR||''')
          AND TABLE_NAME               = UPPER('''||:TABLE_NAME_STR||''')
          AND CHARACTER_MAXIMUM_LENGTH IS NOT NULL
          AND CHARACTER_MAXIMUM_LENGTH < 16777216
        ORDER BY ORDINAL_POSITION';
  
    LET COLUMN_INFO RESULTSET := (EXECUTE IMMEDIATE :QUERY);

    FOR REC IN COLUMN_INFO
    DO
        LET curr_col STRING := REC.column_name;
        
        -- Find the actual max length of the data in this column
        QUERY := 'SELECT MAX(LENGTH(' || :curr_col || ')) FROM ' || :TABLE_NAME_STR;
        LET RES1 RESULTSET := (EXECUTE IMMEDIATE :QUERY);
        LET CURRENT_COL_MAX_LEN INT := 0;
        LET CUR1 CURSOR FOR RES1;
        OPEN CUR1;
        FETCH CUR1 INTO CURRENT_COL_MAX_LEN;
        CLOSE CUR1;
       
        FINAL_QUERY := FINAL_QUERY || ' CAST('|| curr_col || ' AS VARCHAR('|| CURRENT_COL_MAX_LEN || ')) AS '|| curr_col || ',';
    END FOR;

    FINAL_QUERY := LEFT(FINAL_QUERY, LENGTH(FINAL_QUERY) - 1); --REMOVE LAST COMMA
    FINAL_QUERY := FINAL_QUERY || ' FROM '||TABLE_NAME_STR || ';';
    EXECUTE IMMEDIATE :FINAL_QUERY;
  
    RETURN 'Table ' || :TABLE_NAME_STR || ' has been right-sized.';
END;
$$;
